<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Python Exception Catching and Handling - SoByte</title>
  <meta name="renderer" content="webkit" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />

<meta name="theme-color" content="#f8f5ec" />
<meta name="msapplication-navbutton-color" content="#f8f5ec">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="#f8f5ec">


<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6356451834813761" crossorigin="anonymous"></script>


<script async src="https://www.googletagmanager.com/gtag/js?id=G-E8GRRGBTEZ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-E8GRRGBTEZ');
</script>


<meta name="author" content="" /><meta name="description" content="What is an exception? An exception is an event that occurs during program execution and affects the normal execution of the program. Typically, an exception occurs when Python is unable to process a program properly. Exceptions are Python objects that represent an error. When an exception occurs in a Python script we need to catch it and handle it, otherwise the program will terminate execution. When an uncaught exception occurs," /><meta name="keywords" content="Python, Exception, Catching, Handling" />






<meta name="generator" content="Hugo 0.92.2 with theme even" />


<link rel="canonical" href="https://www.sobyte.net/post/2021-10/exception-handling-in-python/" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">



<link href="/sass/main.min.f92fd13721ddf72129410fd8250e73152cc6f2438082b6c0208dc24ee7c13fc4.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">


<meta property="og:title" content="Python Exception Catching and Handling" />
<meta property="og:description" content="What is an exception? An exception is an event that occurs during program execution and affects the normal execution of the program. Typically, an exception occurs when Python is unable to process a program properly. Exceptions are Python objects that represent an error. When an exception occurs in a Python script we need to catch it and handle it, otherwise the program will terminate execution. When an uncaught exception occurs," />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://www.sobyte.net/post/2021-10/exception-handling-in-python/" /><meta property="article:section" content="post" />
<meta property="article:published_time" content="2021-10-22T14:25:41+08:00" />
<meta property="article:modified_time" content="2021-10-22T14:25:41+08:00" />

<meta itemprop="name" content="Python Exception Catching and Handling">
<meta itemprop="description" content="What is an exception? An exception is an event that occurs during program execution and affects the normal execution of the program. Typically, an exception occurs when Python is unable to process a program properly. Exceptions are Python objects that represent an error. When an exception occurs in a Python script we need to catch it and handle it, otherwise the program will terminate execution. When an uncaught exception occurs,"><meta itemprop="datePublished" content="2021-10-22T14:25:41+08:00" />
<meta itemprop="dateModified" content="2021-10-22T14:25:41+08:00" />
<meta itemprop="wordCount" content="2807">
<meta itemprop="keywords" content="python," /><meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Python Exception Catching and Handling"/>
<meta name="twitter:description" content="What is an exception? An exception is an event that occurs during program execution and affects the normal execution of the program. Typically, an exception occurs when Python is unable to process a program properly. Exceptions are Python objects that represent an error. When an exception occurs in a Python script we need to catch it and handle it, otherwise the program will terminate execution. When an uncaught exception occurs,"/>

<!--[if lte IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/classlist/1.1.20170427/classList.min.js"></script>
<![endif]-->

<!--[if lt IE 9]>
  <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
<![endif]-->

</head>
<body>
  <div id="mobile-navbar" class="mobile-navbar">
  <div class="mobile-header-logo">
    <a href="/" class="logo">SoByte</a>
  </div>
  <div class="mobile-navbar-icon">
    <span></span>
    <span></span>
    <span></span>
  </div>
</div>
<nav id="mobile-menu" class="mobile-menu slideout-menu">
  <ul class="mobile-menu-list">
    <a href="/">
        <li class="mobile-menu-item">Home</li>
      </a><a href="/post/">
        <li class="mobile-menu-item">Archives</li>
      </a><a href="/tags/">
        <li class="mobile-menu-item">Tags</li>
      </a><a href="/categories/">
        <li class="mobile-menu-item">Categories</li>
      </a><a href="/about/">
        <li class="mobile-menu-item">About</li>
      </a><a href="/ukraine/">
        <li class="mobile-menu-item">UKRAINE</li>
      </a>
  </ul>

  


</nav>

  <div class="container" id="mobile-panel">
    <header id="header" class="header">
        <div class="logo-wrapper">
  <a href="/" class="logo">SoByte</a>
</div>





<nav class="site-navbar">
  <ul id="menu" class="menu">
    <li class="menu-item">
        <a class="menu-item-link" href="/">Home</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/post/">Archives</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/tags/">Tags</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/categories/">Categories</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/about/">About</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/ukraine/">UKRAINE</a>
      </li>
  </ul>
</nav>

    </header>

    <main id="main" class="main">
      <div class="content-wrapper">
        <div id="content" class="content">
          <article class="post">
    
    <header class="post-header">
      <h1 class="post-title">Python Exception Catching and Handling</h1>

      <div class="post-meta">
        <span class="post-time"> 2021-10-22 14:25:41 </span>
        <div class="post-category">
            <a href="/categories/skills/"> skills </a>
            </div>
          <span class="more-meta"> 2807 words </span>
          <span class="more-meta"> 6 mins read </span>
        
      </div>
    </header>

    <div class="post-toc" id="post-toc">
  <h2 class="post-toc-title">Contents</h2>
  <div class="post-toc-content">
    <nav id="TableOfContents">
  <ul>
    <li>
      <ul>
        <li><a href="#what-is-an-exception">What is an exception?</a></li>
        <li><a href="#exception-catching-and-handling">Exception catching and handling</a></li>
        <li><a href="#raise-manually-raise-an-exception">raise: manually raise an exception</a></li>
        <li><a href="#custom-exceptions">Custom Exceptions</a></li>
        <li><a href="#assertion-assert-condition">Assertion: assert condition</a></li>
        <li><a href="#traceback-get-detailed-exception-information">traceback Get detailed exception information</a></li>
      </ul>
    </li>
  </ul>
</nav>
  </div>
</div>
    <div class="post-content">
      <h2 id="what-is-an-exception">What is an exception?</h2>
<p>An exception is an event that occurs during program execution and affects the normal execution of the program. Typically, an exception occurs when Python is unable to process a program properly. Exceptions are Python objects that represent an error. When an exception occurs in a Python script we need to catch it and handle it, otherwise the program will terminate execution.</p>
<p>When an uncaught exception occurs, Python will end the program and print a stack trace message, along with the exception name and additional information. The details are as follows.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span><span class="lnt">5
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-py" data-lang="py"><span class="o">&gt;&gt;&gt;</span> <span class="n">a</span> <span class="o">=</span> <span class="mi">1</span><span class="o">/</span><span class="mi">0</span>
<span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="s2">&#34;&lt;pyshell#1&gt;&#34;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
    <span class="n">a</span> <span class="o">=</span> <span class="mi">1</span><span class="o">/</span><span class="mi">0</span>
<span class="ne">ZeroDivisionError</span><span class="p">:</span> <span class="n">division</span> <span class="n">by</span> <span class="n">zero</span>
</code></pre></td></tr></table>
</div>
</div><p>Broadly speaking, errors are classified as errors and exceptions</p>
<ul>
<li>Errors usually refer to syntax errors, which can be avoided artificially</li>
<li>Exceptions are problems that occur when the syntax is logically correct</li>
</ul>
<p><img src="https://cdn.jsdelivr.net/gh/b0xt/sobyte-images/2021/10/22/3b4fd86e6a8347f2b6f2527e56b90f00.png" alt=""></p>
<p>The main purposes of catching and handling exceptions in Python are.</p>
<ul>
<li>Error handling: In the event of a runtime error, the application may terminate unconditionally. Using exception handling, we can handle failure cases and avoid program termination.</li>
<li>Code separation: Error handling helps us to separate the code required for error handling from the main logic. The code associated with the error can be placed in an &ldquo;except&rdquo; block, which isolates it from the regular code containing the application logic.</li>
<li>Error differentiation: helps us isolate the different types of errors encountered during execution. We can have multiple &ldquo;except&rdquo; blocks, each dealing with a specific type of error.</li>
</ul>
<p>Other applications.</p>
<ul>
<li>Event notification: Exceptions can also be used as signals for certain conditions, without the need to pass result flags or test them explicitly in the program.</li>
<li>Special case handling: Sometimes there are situations that rarely occur and it is better to change the corresponding handling code to exception handling.</li>
<li>Special control flow: Exceptions are a high level &ldquo;goto&rdquo; that can be used as a basis for implementing special control flow. Such as reverse tracing, etc.</li>
</ul>
<p>Python comes with a very powerful exception handling mechanism, providing many built-in exception classes that provide accurate feedback to the user. Python automatically puts all exception names in a built-in namespace, so programs don&rsquo;t have to import the exceptions module to use exceptions.</p>
<p>Python&rsquo;s built-in exception class inheritance hierarchy is as follows.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt"> 1
</span><span class="lnt"> 2
</span><span class="lnt"> 3
</span><span class="lnt"> 4
</span><span class="lnt"> 5
</span><span class="lnt"> 6
</span><span class="lnt"> 7
</span><span class="lnt"> 8
</span><span class="lnt"> 9
</span><span class="lnt">10
</span><span class="lnt">11
</span><span class="lnt">12
</span><span class="lnt">13
</span><span class="lnt">14
</span><span class="lnt">15
</span><span class="lnt">16
</span><span class="lnt">17
</span><span class="lnt">18
</span><span class="lnt">19
</span><span class="lnt">20
</span><span class="lnt">21
</span><span class="lnt">22
</span><span class="lnt">23
</span><span class="lnt">24
</span><span class="lnt">25
</span><span class="lnt">26
</span><span class="lnt">27
</span><span class="lnt">28
</span><span class="lnt">29
</span><span class="lnt">30
</span><span class="lnt">31
</span><span class="lnt">32
</span><span class="lnt">33
</span><span class="lnt">34
</span><span class="lnt">35
</span><span class="lnt">36
</span><span class="lnt">37
</span><span class="lnt">38
</span><span class="lnt">39
</span><span class="lnt">40
</span><span class="lnt">41
</span><span class="lnt">42
</span><span class="lnt">43
</span><span class="lnt">44
</span><span class="lnt">45
</span><span class="lnt">46
</span><span class="lnt">47
</span><span class="lnt">48
</span><span class="lnt">49
</span><span class="lnt">50
</span><span class="lnt">51
</span><span class="lnt">52
</span><span class="lnt">53
</span><span class="lnt">54
</span><span class="lnt">55
</span><span class="lnt">56
</span><span class="lnt">57
</span><span class="lnt">58
</span><span class="lnt">59
</span><span class="lnt">60
</span><span class="lnt">61
</span><span class="lnt">62
</span><span class="lnt">63
</span><span class="lnt">64
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-text" data-lang="text">BaseException  # 所有异常的基类
 -- SystemExit  # 解释器请求退出
 -- KeyboardInterrupt  # 用户中断执行(通常是输入^C)
 -- GeneratorExit  # 生成器(generator)发生异常来通知退出
 -- Exception  # 常规异常的基类
      -- StopIteration  # 迭代器没有更多的值
      -- StopAsyncIteration  # 必须通过异步迭代器对象的__anext__()方法引发以停止迭代
      -- ArithmeticError  # 各种算术错误引发的内置异常的基类
      |    -- FloatingPointError  # 浮点计算错误
      |    -- OverflowError  # 数值运算结果太大无法表示
      |    -- ZeroDivisionError  # 除(或取模)零 (所有数据类型)
      -- AssertionError  # 当assert语句失败时引发
      -- AttributeError  # 属性引用或赋值失败
      -- BufferError  # 无法执行与缓冲区相关的操作时引发
      -- EOFError  # 当input()函数在没有读取任何数据的情况下达到文件结束条件(EOF)时引发
      -- ImportError  # 导入模块/对象失败
      |    -- ModuleNotFoundError  # 无法找到模块或在在sys.modules中找到None
      -- LookupError  # 映射或序列上使用的键或索引无效时引发的异常的基类
      |    -- IndexError  # 序列中没有此索引(index)
      |    -- KeyError  # 映射中没有这个键
      -- MemoryError  # 内存溢出错误(对于Python 解释器不是致命的)
      -- NameError  # 未声明/初始化对象 (没有属性)
      |    -- UnboundLocalError  # 访问未初始化的本地变量
      -- OSError  # 操作系统错误，EnvironmentError，IOError，WindowsError，socket.error，select.error和mmap.error已合并到OSError中，构造函数可能返回子类
      |    -- BlockingIOError  # 操作将阻塞对象(e.g. socket)设置为非阻塞操作
      |    -- ChildProcessError  # 在子进程上的操作失败
      |    -- ConnectionError  # 与连接相关的异常的基类
      |    |    -- BrokenPipeError  # 另一端关闭时尝试写入管道或试图在已关闭写入的套接字上写入
      |    |    -- ConnectionAbortedError  # 连接尝试被对等方中止
      |    |    -- ConnectionRefusedError  # 连接尝试被对等方拒绝
      |    |    -- ConnectionResetError    # 连接由对等方重置
      |    -- FileExistsError  # 创建已存在的文件或目录
      |    -- FileNotFoundError  # 请求不存在的文件或目录
      |    -- InterruptedError  # 系统调用被输入信号中断
      |    -- IsADirectoryError  # 在目录上请求文件操作(例如 os.remove())
      |    -- NotADirectoryError  # 在不是目录的事物上请求目录操作(例如 os.listdir())
      |    -- PermissionError  # 尝试在没有足够访问权限的情况下运行操作
      |    -- ProcessLookupError  # 给定进程不存在
      |    -- TimeoutError  # 系统函数在系统级别超时
      -- ReferenceError  # weakref.proxy()函数创建的弱引用试图访问已经垃圾回收了的对象
      -- RuntimeError  # 在检测到不属于任何其他类别的错误时触发
      |    -- NotImplementedError  # 在用户定义的基类中，抽象方法要求派生类重写该方法或者正在开发的类指示仍然需要添加实际实现
      |    -- RecursionError  # 解释器检测到超出最大递归深度
      -- SyntaxError  # Python 语法错误
      |    -- IndentationError  # 缩进错误
      |         -- TabError  # Tab和空格混用
      -- SystemError  # 解释器发现内部错误
      -- TypeError  # 操作或函数应用于不适当类型的对象
      -- ValueError  # 操作或函数接收到具有正确类型但值不合适的参数
      |    -- UnicodeError  # 发生与Unicode相关的编码或解码错误
      |         -- UnicodeDecodeError  # Unicode解码错误
      |         -- UnicodeEncodeError  # Unicode编码错误
      |         -- UnicodeTranslateError  # Unicode转码错误
      -- Warning  # 警告的基类
           -- DeprecationWarning  # 有关已弃用功能的警告的基类
           -- PendingDeprecationWarning  # 有关不推荐使用功能的警告的基类
           -- RuntimeWarning  # 有关可疑的运行时行为的警告的基类
           -- SyntaxWarning  # 关于可疑语法警告的基类
           -- UserWarning  # 用户代码生成警告的基类
           -- FutureWarning  # 有关已弃用功能的警告的基类
           -- ImportWarning  # 关于模块导入时可能出错的警告的基类
           -- UnicodeWarning  # 与Unicode相关的警告的基类
           -- BytesWarning  # 与bytes和bytearray相关的警告的基类
           -- ResourceWarning  # 与资源使用相关的警告的基类。被默认警告过滤器忽略。
</code></pre></td></tr></table>
</div>
</div><h2 id="exception-catching-and-handling">Exception catching and handling</h2>
<p>We can&rsquo;t guarantee that the programs we write will always run correctly, and the purpose of exception catching and handling is to ensure that the worst-case problems the program gets are managed properly.</p>
<p>In Python, exceptions are caught and handled with try except statement blocks, the basic syntactic structure of which is shown below.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt"> 1
</span><span class="lnt"> 2
</span><span class="lnt"> 3
</span><span class="lnt"> 4
</span><span class="lnt"> 5
</span><span class="lnt"> 6
</span><span class="lnt"> 7
</span><span class="lnt"> 8
</span><span class="lnt"> 9
</span><span class="lnt">10
</span><span class="lnt">11
</span><span class="lnt">12
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-py" data-lang="py"><span class="k">try</span><span class="p">:</span>
    <span class="n">可能产生异常的代码块</span>
<span class="k">except</span> <span class="p">[</span> <span class="p">(</span><span class="n">Error1</span><span class="p">,</span> <span class="n">Error2</span><span class="p">,</span> <span class="o">...</span> <span class="p">)</span> <span class="p">[</span><span class="k">as</span> <span class="n">e</span><span class="p">]</span> <span class="p">]:</span>
    <span class="n">处理异常的代码块1</span>
<span class="k">except</span> <span class="p">[</span> <span class="p">(</span><span class="n">Error3</span><span class="p">,</span> <span class="n">Error4</span><span class="p">,</span> <span class="o">...</span> <span class="p">)</span> <span class="p">[</span><span class="k">as</span> <span class="n">e</span><span class="p">]</span> <span class="p">]:</span>
    <span class="n">处理异常的代码块2</span>
<span class="k">except</span>  <span class="p">[</span><span class="ne">Exception</span><span class="p">]:</span>
    <span class="n">处理其它异常</span>
<span class="k">else</span><span class="p">:</span>
    <span class="n">没有异常时执行的代码块</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="n">不管有没有异常都会执行的代码块</span>
</code></pre></td></tr></table>
</div>
</div><p><img src="https://cdn.jsdelivr.net/gh/b0xt/sobyte-images/2021/10/22/48a4e25c95a9466d84d7de797e362e6b.png" alt=""></p>
<p>The way try works is that when you start a try statement, python marks it in the context of the current program so that you can return to it when an exception occurs, the try clause is executed first, and what happens next depends on whether an exception occurs during execution.</p>
<p>If an exception occurs while the statement after try is executing, Python jumps back to try and executes the first exception clause that matches the exception, the exception is handled, and control flows through the entire try statement (unless a new exception is raised while the exception is being handled). If an exception occurs in the statement after try and there is no matching except clause, the exception is passed to the upper level of try, or to the top level of the program (which will end the program and print the default error message). If no exception occurs during the execution of the try clause, Python will execute the statement after the else statement (if there is an else), and then control flows through the entire try statement.</p>
<p>Code example.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt"> 1
</span><span class="lnt"> 2
</span><span class="lnt"> 3
</span><span class="lnt"> 4
</span><span class="lnt"> 5
</span><span class="lnt"> 6
</span><span class="lnt"> 7
</span><span class="lnt"> 8
</span><span class="lnt"> 9
</span><span class="lnt">10
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-py" data-lang="py"><span class="k">try</span><span class="p">:</span>
    <span class="n">file_reader</span> <span class="o">=</span> <span class="nb">open</span><span class="p">(</span><span class="s2">&#34;a.json&#34;</span><span class="p">)</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">file_reader</span><span class="o">.</span><span class="n">read</span><span class="p">())</span>
<span class="k">except</span> <span class="ne">FileNotFoundError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;The File Cannot be Found&#34;</span><span class="p">)</span>
<span class="k">except</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;This is the Generic Error&#34;</span><span class="p">)</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;Closing File Reader...&#34;</span><span class="p">)</span>
    <span class="n">file_reader</span><span class="o">.</span><span class="n">close</span><span class="p">()</span>
</code></pre></td></tr></table>
</div>
</div><p>The Exception class is the parent of all Python exception classes, so except Exception will be able to catch any exception; in other words, it is the catch-all exception handling syntax. There is one kind of error that there is no way to catch: indentation errors.</p>
<h2 id="raise-manually-raise-an-exception">raise: manually raise an exception</h2>
<p>Sometimes an exception can be used as a flag for code to run, and by proactively triggering an exception you can change the course of the code, thus improving code robustness.</p>
<p><img src="https://cdn.jsdelivr.net/gh/b0xt/sobyte-images/2021/10/22/36fa011cd24340519b304feac3f60e55.png" alt=""></p>
<p>The active trigger exception requires the raise keyword, which has the following syntax structure.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-py" data-lang="py"><span class="k">raise</span> <span class="p">[</span><span class="ne">Exception</span> <span class="p">[,</span> <span class="n">args</span> <span class="p">[,</span> <span class="n">traceback</span><span class="p">]]]</span>
</code></pre></td></tr></table>
</div>
</div><p>Example.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span><span class="lnt">5
</span><span class="lnt">6
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-py" data-lang="py"><span class="k">try</span><span class="p">:</span>
    <span class="n">a</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="nb">input</span><span class="p">(</span><span class="s2">&#34;Enter a positive integer value: &#34;</span><span class="p">))</span>
    <span class="k">if</span> <span class="n">a</span> <span class="o">&lt;=</span> <span class="mi">0</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="s2">&#34;This is not a positive number!!&#34;</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">ValueError</span> <span class="k">as</span> <span class="n">ve</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">ve</span><span class="p">)</span>
</code></pre></td></tr></table>
</div>
</div><p>The statement Exception is the type of the exception (e.g., ValueError) The parameter is an exception parameter value. This parameter is optional, and if not provided, the exception parameter is &ldquo;None&rdquo;. The last parameter is optional (rarely used in practice) and, if present, is a trace exception object.</p>
<h2 id="custom-exceptions">Custom Exceptions</h2>
<p>You can have your own exceptions by creating a new exception class. Exception classes inherit from the Exception class, either directly, or indirectly, e.g.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt"> 1
</span><span class="lnt"> 2
</span><span class="lnt"> 3
</span><span class="lnt"> 4
</span><span class="lnt"> 5
</span><span class="lnt"> 6
</span><span class="lnt"> 7
</span><span class="lnt"> 8
</span><span class="lnt"> 9
</span><span class="lnt">10
</span><span class="lnt">11
</span><span class="lnt">12
</span><span class="lnt">13
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-py" data-lang="py"><span class="k">class</span> <span class="nc">MyError</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span>
    <span class="k">def</span> <span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">value</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">value</span> <span class="o">=</span> <span class="n">value</span>

    <span class="k">def</span> <span class="fm">__str__</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="k">return</span> <span class="nb">repr</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">value</span><span class="p">)</span>


<span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="n">MyError</span><span class="p">(</span><span class="mi">2</span> <span class="o">*</span> <span class="mi">2</span><span class="p">)</span>
    <span class="c1"># raise MyError(&#39;oops!&#39;)</span>
<span class="k">except</span> <span class="n">MyError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;My exception occurred, value:&#39;</span><span class="p">,</span> <span class="n">e</span><span class="o">.</span><span class="n">value</span><span class="p">)</span>
</code></pre></td></tr></table>
</div>
</div><h2 id="assertion-assert-condition">Assertion: assert condition</h2>
<p>Python assert is used to determine an expression and trigger an exception if the condition of the expression is false. Assertions can return an error directly if the condition is not met, without having to wait for the program to run and then crash. For example, if our code can only run on Linux, we can first determine if the current system meets the condition.</p>
<p><img src="https://cdn.jsdelivr.net/gh/b0xt/sobyte-images/2021/10/22/1dc26c0b71ac439486b2e19012c5907c.png" alt=""></p>
<p>The syntax format is as follows.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-py" data-lang="py"><span class="k">assert</span> <span class="n">expression</span>
</code></pre></td></tr></table>
</div>
</div><p>Equivalent to.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-py" data-lang="py"><span class="k">if</span> <span class="ow">not</span> <span class="n">expression</span><span class="p">:</span>
    <span class="k">raise</span> <span class="ne">AssertionError</span><span class="p">(</span><span class="n">arguments</span><span class="p">)</span>
</code></pre></td></tr></table>
</div>
</div><p>Example.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-py" data-lang="py"><span class="kn">import</span> <span class="nn">sys</span>
<span class="k">assert</span> <span class="p">(</span><span class="s1">&#39;linux&#39;</span> <span class="ow">in</span> <span class="n">sys</span><span class="o">.</span><span class="n">platform</span><span class="p">),</span> <span class="s2">&#34;该代码只能在 Linux 下执行&#34;</span>
</code></pre></td></tr></table>
</div>
</div><p>assert looks good, however it is not pleasant to use. For example, someone tells you that the program is wrong, but doesn&rsquo;t tell you what&rsquo;s wrong. Many times such assert is better than not writing it at all. A common solution is to use a testing framework or other packages instead: py.test, unittest, ptest, assertpy&hellip;</p>
<h2 id="traceback-get-detailed-exception-information">traceback Get detailed exception information</h2>
<p>The output of try&hellip;except&hellip; only lets you know that the error was reported, but not in which file, function, or line. Using the traceback module, you can get a very clear picture of where the error is.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span><span class="lnt">5
</span><span class="lnt">6
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-py" data-lang="py"><span class="kn">import</span> <span class="nn">traceback</span>

<span class="k">try</span><span class="p">:</span>
    <span class="mi">1</span> <span class="o">/</span> <span class="mi">0</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="n">traceback</span><span class="o">.</span><span class="n">print_exc</span><span class="p">()</span>
</code></pre></td></tr></table>
</div>
</div><p>Output.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-py" data-lang="py"><span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
<span class="n">File</span> <span class="s2">&#34;test_traceback.py&#34;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">3</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
<span class="mi">1</span><span class="o">/</span><span class="mi">0</span>
<span class="ne">ZeroDivisionError</span><span class="p">:</span> <span class="n">integer</span> <span class="n">division</span> <span class="ow">or</span> <span class="n">modulo</span> <span class="n">by</span> <span class="n">zero</span>
</code></pre></td></tr></table>
</div>
</div><p>Python programs get their traceback information from an object called the traceback object, which is usually obtained through the function sys.exc_info().</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt"> 1
</span><span class="lnt"> 2
</span><span class="lnt"> 3
</span><span class="lnt"> 4
</span><span class="lnt"> 5
</span><span class="lnt"> 6
</span><span class="lnt"> 7
</span><span class="lnt"> 8
</span><span class="lnt"> 9
</span><span class="lnt">10
</span><span class="lnt">11
</span><span class="lnt">12
</span><span class="lnt">13
</span><span class="lnt">14
</span><span class="lnt">15
</span><span class="lnt">16
</span><span class="lnt">17
</span><span class="lnt">18
</span><span class="lnt">19
</span><span class="lnt">20
</span><span class="lnt">21
</span><span class="lnt">22
</span><span class="lnt">23
</span><span class="lnt">24
</span><span class="lnt">25
</span><span class="lnt">26
</span><span class="lnt">27
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-py" data-lang="py"><span class="kn">import</span> <span class="nn">sys</span>


<span class="k">def</span> <span class="nf">func1</span><span class="p">():</span>
    <span class="k">raise</span> <span class="ne">Exception</span><span class="p">(</span><span class="s2">&#34;--func1 exception--&#34;</span><span class="p">)</span>


<span class="k">def</span> <span class="nf">test1</span><span class="p">():</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">func1</span><span class="p">()</span>
    <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
        <span class="nb">print</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>


<span class="k">def</span> <span class="nf">test2</span><span class="p">():</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">func1</span><span class="p">()</span>
    <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
        <span class="n">exc_type</span><span class="p">,</span> <span class="n">exc_value</span><span class="p">,</span> <span class="n">exc_traceback_obj</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;exc_type: </span><span class="si">%s</span><span class="s2">&#34;</span> <span class="o">%</span> <span class="n">exc_type</span><span class="p">)</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;exc_value: </span><span class="si">%s</span><span class="s2">&#34;</span> <span class="o">%</span> <span class="n">exc_value</span><span class="p">)</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;exc_traceback_obj: </span><span class="si">%s</span><span class="s2">&#34;</span> <span class="o">%</span> <span class="n">exc_traceback_obj</span><span class="p">)</span>


<span class="k">if</span> <span class="vm">__name__</span> <span class="o">==</span> <span class="s1">&#39;__main__&#39;</span><span class="p">:</span>
    <span class="n">test1</span><span class="p">()</span>
    <span class="n">test2</span><span class="p">()</span>
</code></pre></td></tr></table>
</div>
</div><p>Output results.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span><span class="lnt">5
</span><span class="lnt">6
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-text" data-lang="text">--func1 exception--
exc_type: &lt;class &#39;Exception&#39;&gt;
exc_value: --func1 exception--
exc_traceback_obj: &lt;traceback object at 0x0000024D2F6A22C8&gt;

Process finished with exit code 0
</code></pre></td></tr></table>
</div>
</div><p>As we can see from the above example, sys.exc_info() gets the information about the currently handled exception and returns a tuple, the first data of the tuple is the type of the exception, the second return value is the value of the exception, and the third is the traceback object.</p>
<p>With the traceback object we can use the traceback module to print and format the information about the traceback.</p>

    </div>

    
<footer class="post-footer">
      <div class="post-tags">
          <a href="/tags/python/">python</a>
          </div>
      <nav class="post-nav">
        <a class="prev" href="/post/2021-10/pandas/">
            <i class="iconfont icon-left"></i>
            <span class="prev-text nav-default">Pandas Data Processing Concise Tutorial</span>
            <span class="prev-text nav-mobile">Prev</span>
          </a>
        <a class="next" href="/post/2021-10/python-string-format/">
            <span class="next-text nav-default">Python String Formatting Tool</span>
            <span class="next-text nav-mobile">Next</span>
            <i class="iconfont icon-right"></i>
          </a>
      </nav>
    </footer>
  </article>
        </div>
        

  

  

      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="social-links">
  <a href="https://www.sobyte.net/index.xml" type="application/rss+xml" class="iconfont icon-rss" title="rss"></a>
</div>

<div class="copyright">
  <span class="power-by">
    Powered by <a class="hexo-link" href="https://gohugo.io">Hugo</a>
  </span>
  <span class="division">|</span>
  <span class="theme-info">
    Theme - 
    <a class="theme-link" href="https://github.com/olOwOlo/hugo-theme-even">Even</a>
  </span>

  

  <span class="copyright-year">
    &copy; 
    2021 - 
    2022<span class="heart"><i class="iconfont icon-heart"></i></span><span></span>
  </span>
</div>

    </footer>

    <div class="back-to-top" id="back-to-top">
      <i class="iconfont icon-up"></i>
    </div>
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>



<script type="text/javascript" src="/js/main.min.c99b103c33d1539acf3025e1913697534542c4a5aa5af0ccc20475ed2863603b.js"></script>
  <script type="text/javascript">
    window.MathJax = {
      tex: {
        inlineMath: [['$','$'], ['\\(','\\)']],
        tags: 'ams',
        }
    };
  </script>
  <script async src="https://cdn.jsdelivr.net/npm/mathjax@3.0.5/es5/tex-mml-chtml.js" integrity="sha256-HGLuEfFcsUJGhvB8cQ8nr0gai9EucOOaIxFw7qxmd+w=" crossorigin="anonymous"></script>








</body>
</html>
