<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Exceptions and errors that cannot be caught by try-catch statements in js - SoByte</title>
  <meta name="renderer" content="webkit" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />

<meta name="theme-color" content="#f8f5ec" />
<meta name="msapplication-navbutton-color" content="#f8f5ec">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="#f8f5ec">


<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6356451834813761" crossorigin="anonymous"></script>


<script async src="https://www.googletagmanager.com/gtag/js?id=G-E8GRRGBTEZ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-E8GRRGBTEZ');
</script>


<meta name="author" content="" /><meta name="description" content="During development, our goal is 0error, 0warning. But there are many factors beyond our control, and to avoid errors in one piece of code that affect other modules or the overall code, we often use the try-catch module to actively catch some exceptions or errors. For example, if we get the parameters in the url and parse them in JSON, we need to wrap them in try-catch because we can&amp;rsquo;t" /><meta name="keywords" content="javascript, try-catch" />






<meta name="generator" content="Hugo 0.92.2 with theme even" />


<link rel="canonical" href="https://www.sobyte.net/post/2022-02/try-catch-cant-error/" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">



<link href="/sass/main.min.f92fd13721ddf72129410fd8250e73152cc6f2438082b6c0208dc24ee7c13fc4.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">


<meta property="og:title" content="Exceptions and errors that cannot be caught by try-catch statements in js" />
<meta property="og:description" content="During development, our goal is 0error, 0warning. But there are many factors beyond our control, and to avoid errors in one piece of code that affect other modules or the overall code, we often use the try-catch module to actively catch some exceptions or errors. For example, if we get the parameters in the url and parse them in JSON, we need to wrap them in try-catch because we can&rsquo;t" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://www.sobyte.net/post/2022-02/try-catch-cant-error/" /><meta property="article:section" content="post" />
<meta property="article:published_time" content="2022-02-20T13:13:22+08:00" />
<meta property="article:modified_time" content="2022-02-20T13:13:22+08:00" />

<meta itemprop="name" content="Exceptions and errors that cannot be caught by try-catch statements in js">
<meta itemprop="description" content="During development, our goal is 0error, 0warning. But there are many factors beyond our control, and to avoid errors in one piece of code that affect other modules or the overall code, we often use the try-catch module to actively catch some exceptions or errors. For example, if we get the parameters in the url and parse them in JSON, we need to wrap them in try-catch because we can&rsquo;t"><meta itemprop="datePublished" content="2022-02-20T13:13:22+08:00" />
<meta itemprop="dateModified" content="2022-02-20T13:13:22+08:00" />
<meta itemprop="wordCount" content="1618">
<meta itemprop="keywords" content="javascript," /><meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Exceptions and errors that cannot be caught by try-catch statements in js"/>
<meta name="twitter:description" content="During development, our goal is 0error, 0warning. But there are many factors beyond our control, and to avoid errors in one piece of code that affect other modules or the overall code, we often use the try-catch module to actively catch some exceptions or errors. For example, if we get the parameters in the url and parse them in JSON, we need to wrap them in try-catch because we can&rsquo;t"/>

<!--[if lte IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/classlist/1.1.20170427/classList.min.js"></script>
<![endif]-->

<!--[if lt IE 9]>
  <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
<![endif]-->

</head>
<body>
  <div id="mobile-navbar" class="mobile-navbar">
  <div class="mobile-header-logo">
    <a href="/" class="logo">SoByte</a>
  </div>
  <div class="mobile-navbar-icon">
    <span></span>
    <span></span>
    <span></span>
  </div>
</div>
<nav id="mobile-menu" class="mobile-menu slideout-menu">
  <ul class="mobile-menu-list">
    <a href="/">
        <li class="mobile-menu-item">Home</li>
      </a><a href="/post/">
        <li class="mobile-menu-item">Archives</li>
      </a><a href="/tags/">
        <li class="mobile-menu-item">Tags</li>
      </a><a href="/categories/">
        <li class="mobile-menu-item">Categories</li>
      </a><a href="/about/">
        <li class="mobile-menu-item">About</li>
      </a><a href="/ukraine/">
        <li class="mobile-menu-item">UKRAINE</li>
      </a>
  </ul>

  


</nav>

  <div class="container" id="mobile-panel">
    <header id="header" class="header">
        <div class="logo-wrapper">
  <a href="/" class="logo">SoByte</a>
</div>





<nav class="site-navbar">
  <ul id="menu" class="menu">
    <li class="menu-item">
        <a class="menu-item-link" href="/">Home</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/post/">Archives</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/tags/">Tags</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/categories/">Categories</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/about/">About</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/ukraine/">UKRAINE</a>
      </li>
  </ul>
</nav>

    </header>

    <main id="main" class="main">
      <div class="content-wrapper">
        <div id="content" class="content">
          <article class="post">
    
    <header class="post-header">
      <h1 class="post-title">Exceptions and errors that cannot be caught by try-catch statements in js</h1>

      <div class="post-meta">
        <span class="post-time"> 2022-02-20 13:13:22 </span>
        <div class="post-category">
            <a href="/categories/tutorials/"> tutorials </a>
            </div>
          <span class="more-meta"> 1618 words </span>
          <span class="more-meta"> 4 mins read </span>
        
      </div>
    </header>

    <div class="post-toc" id="post-toc">
  <h2 class="post-toc-title">Contents</h2>
  <div class="post-toc-content">
    <nav id="TableOfContents">
  <ul>
    <li>
      <ul>
        <li><a href="#1-what-errors-cant-be-caught-by-try-catch">1. What errors can&rsquo;t be caught by try-catch</a>
          <ul>
            <li><a href="#11-cross-domain-errors">1.1 Cross-domain errors</a></li>
            <li><a href="#12-asynchronous-errors">1.2 Asynchronous errors</a></li>
            <li><a href="#13-how-to-catch-exceptions-in-async-await">1.3 How to catch exceptions in async-await</a></li>
            <li><a href="#14-multi-layer-try-catch">1.4 Multi-layer try-catch</a></li>
          </ul>
        </li>
        <li><a href="#2-native-error-types">2. Native error types</a>
          <ul>
            <li><a href="#21-syntaxerror">2.1 SyntaxError</a></li>
            <li><a href="#22-typeerror">2.2 TypeError</a></li>
            <li><a href="#23-rangeerror">2.3 RangeError</a></li>
            <li><a href="#24-evalerror">2.4 evalError</a></li>
            <li><a href="#25-referenceerror">2.5 ReferenceError</a></li>
            <li><a href="#26-uri-errors-urierror">2.6 URI errors (URIError)</a></li>
          </ul>
        </li>
        <li><a href="#3-customizing-error-types">3. Customizing error types</a></li>
        <li><a href="#4-summary">4. Summary</a></li>
      </ul>
    </li>
  </ul>
</nav>
  </div>
</div>
    <div class="post-content">
      <p>During development, our goal is 0error, 0warning.</p>
<p>But there are many factors beyond our control, and to avoid errors in one piece of code that affect other modules or the overall code, we often use the <code>try-catch</code> module to actively catch some exceptions or errors.</p>
<p>For example, if we get the parameters in the url and parse them in JSON, we need to wrap them in <code>try-catch</code> because we can&rsquo;t guarantee that the parameters we get will be parsed properly.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span><span class="lnt">5
</span><span class="lnt">6
</span><span class="lnt">7
</span><span class="lnt">8
</span><span class="lnt">9
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-js" data-lang="js"><span class="kr">const</span> <span class="nx">addparams</span> <span class="o">=</span> <span class="nx">getQueryString</span><span class="p">(</span><span class="s1">&#39;_addparams&#39;</span><span class="p">);</span>
<span class="k">if</span> <span class="p">(</span><span class="nx">addparams</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">try</span> <span class="p">{</span>
    <span class="kr">const</span> <span class="p">{</span> <span class="nx">openid</span><span class="p">,</span> <span class="nx">token</span> <span class="p">}</span> <span class="o">=</span> <span class="nx">JSON</span><span class="p">.</span><span class="nx">parse</span><span class="p">(</span><span class="nx">addparams</span><span class="p">);</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">openid</span><span class="p">,</span> <span class="nx">token</span><span class="p">);</span>
  <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">err</span><span class="p">)</span> <span class="p">{</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">err</span><span class="p">);</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre></td></tr></table>
</div>
</div><p>It is possible that the user may intentionally or unintentionally copy the link incompletely, resulting in an incomplete parameter. <code>JSON.parse</code> cannot parse incomplete json string.</p>
<p>To avoid JSON parsing errors caused by incomplete data, we can include it with <code>try-catch</code>.</p>
<h2 id="1-what-errors-cant-be-caught-by-try-catch">1. What errors can&rsquo;t be caught by try-catch</h2>
<p>We often use the <code>try-catch</code> module to actively catch some exceptions or errors, so that this block of code does not affect other modules or the overall code. But there are some cases where try-catch does not catch an exception in the code!</p>
<h3 id="11-cross-domain-errors">1.1 Cross-domain errors</h3>
<p>When we use xhr to request an interface, the browser will prompt an error in the console if the interface does not support cross-domain.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-text" data-lang="text">Access to XMLHttpRequest at &#39;https://xxxxxxx.qq.com/qq/userInfo&#39; from origin &#39;https://www.xiabingbao.com&#39; has been blocked by CORS policy: No &#39;Access-Control-Allow-Origin&#39; header is present on the requested resource
</code></pre></td></tr></table>
</div>
</div><p><img src="https://cdn.jsdelivr.net/gh/b0xt/sobyte-images/2022/02/20/1831c8caa5fe4f9b8c25f8ff6ea3cb66.png" alt="sobyte"></p>
<p>As we can see in the image, the request for the interface is generating a cross domain error, but it&rsquo;s not going to <code>catch</code>.</p>
<p>Previously, when I was doing canvas compositing, the domain name of some images did not support cross-domain, so I wanted to request the image directly first, and if the image was cross-domain, then request the backend interface, which would convert the image to base64, but in the process of testing, I found that this cross-domain error would definitely be shown. However, I didn&rsquo;t want to show it to the caller in the first place, because I had already set up a tuck-in solution. But you can&rsquo;t trot out the error with try-catch.</p>
<p>Of course, this doesn&rsquo;t mean that the front-end doesn&rsquo;t know that a cross-domain error was generated. We can know that the xhr request generated a request error by listening to xhr.onerror.</p>
<h3 id="12-asynchronous-errors">1.2 Asynchronous errors</h3>
<p>If an error is generated by an asynchronous module in try, catch will not catch it, for example.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt"> 1
</span><span class="lnt"> 2
</span><span class="lnt"> 3
</span><span class="lnt"> 4
</span><span class="lnt"> 5
</span><span class="lnt"> 6
</span><span class="lnt"> 7
</span><span class="lnt"> 8
</span><span class="lnt"> 9
</span><span class="lnt">10
</span><span class="lnt">11
</span><span class="lnt">12
</span><span class="lnt">13
</span><span class="lnt">14
</span><span class="lnt">15
</span><span class="lnt">16
</span><span class="lnt">17
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-js" data-lang="js"><span class="c1">// setTimeout中的错误
</span><span class="c1"></span><span class="k">try</span> <span class="p">{</span>
  <span class="nx">setTimeout</span><span class="p">(</span><span class="kd">function</span> <span class="p">()</span> <span class="p">{</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="s1">&#39;error in setTimeout&#39;</span><span class="p">);</span> <span class="c1">// 200ms后会把异常抛出到全局
</span><span class="c1"></span>  <span class="p">},</span> <span class="mi">200</span><span class="p">);</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">err</span><span class="p">)</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="s1">&#39;catch error&#39;</span><span class="p">,</span> <span class="nx">err</span><span class="p">);</span> <span class="c1">// 不会执行
</span><span class="c1"></span><span class="p">}</span>

<span class="c1">// Promise中的错误
</span><span class="c1"></span><span class="k">try</span> <span class="p">{</span>
  <span class="nb">Promise</span><span class="p">.</span><span class="nx">resolve</span><span class="p">().</span><span class="nx">then</span><span class="p">(()</span> <span class="p">=&gt;</span> <span class="p">{</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="s1">&#39;error in Promise.then&#39;</span><span class="p">);</span>
  <span class="p">});</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">err</span><span class="p">)</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="s1">&#39;catch error&#39;</span><span class="p">,</span> <span class="nx">err</span><span class="p">);</span>
<span class="p">}</span>
</code></pre></td></tr></table>
</div>
</div><p><img src="https://cdn.jsdelivr.net/gh/b0xt/sobyte-images/2022/02/20/4a255e1d11a240e58bb01f2d825a620d.png" alt="sobyte"></p>
<p>As you can see by the runtime results in the image, both of these codes, do not go into the catch module.</p>
<p>So how should we catch this asynchronous error? The answer is to put the try-catch inside the asynchronous code.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt"> 1
</span><span class="lnt"> 2
</span><span class="lnt"> 3
</span><span class="lnt"> 4
</span><span class="lnt"> 5
</span><span class="lnt"> 6
</span><span class="lnt"> 7
</span><span class="lnt"> 8
</span><span class="lnt"> 9
</span><span class="lnt">10
</span><span class="lnt">11
</span><span class="lnt">12
</span><span class="lnt">13
</span><span class="lnt">14
</span><span class="lnt">15
</span><span class="lnt">16
</span><span class="lnt">17
</span><span class="lnt">18
</span><span class="lnt">19
</span><span class="lnt">20
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-js" data-lang="js"><span class="c1">// 将try-catch放到setTimeout内部
</span><span class="c1"></span><span class="nx">setTimeout</span><span class="p">(()</span> <span class="p">=&gt;</span> <span class="p">{</span>
  <span class="k">try</span> <span class="p">{</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="s1">&#39;error in setTimeout&#39;</span><span class="p">);</span>
  <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">err</span><span class="p">)</span> <span class="p">{</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="s1">&#39;catch error&#39;</span><span class="p">,</span> <span class="nx">err</span><span class="p">);</span>
  <span class="p">}</span>
<span class="p">},</span> <span class="mi">200</span><span class="p">);</span>

<span class="c1">// 将try-catch放到then内部
</span><span class="c1"></span><span class="nb">Promise</span><span class="p">.</span><span class="nx">resolve</span><span class="p">().</span><span class="nx">then</span><span class="p">(()</span> <span class="p">=&gt;</span> <span class="p">{</span>
  <span class="k">try</span> <span class="p">{</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="s1">&#39;error in Promise.then&#39;</span><span class="p">);</span>
  <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">err</span><span class="p">)</span> <span class="p">{</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="s1">&#39;catch error&#39;</span><span class="p">,</span> <span class="nx">err</span><span class="p">);</span>
  <span class="p">}</span>
<span class="p">});</span>

<span class="c1">// 使用Promse自带的catch捕获异常
</span><span class="c1"></span><span class="nb">Promise</span><span class="p">.</span><span class="nx">resolve</span><span class="p">()</span>
</code></pre></td></tr></table>
</div>
</div><p>One great advantage of Promise is that it comes with an exception catch method <code>catch()</code> that automatically goes to the catch() method when the then() method generates an error that prevents the code from running. So it is recommended to write Promise with catch() on it, otherwise uncaught exceptions will bubble up to the global level.</p>
<h3 id="13-how-to-catch-exceptions-in-async-await">1.3 How to catch exceptions in async-await</h3>
<p>The syntactic sugar of <code>async-await</code> allows us to write Promise like synchronous code, so how do we catch exceptions in async-await?</p>
<p>Here we would normally use <code>try-catch</code> to catch exceptions.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span><span class="lnt">5
</span><span class="lnt">6
</span><span class="lnt">7
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-js" data-lang="js"><span class="kr">const</span> <span class="nx">request</span> <span class="o">=</span> <span class="kr">async</span> <span class="p">()</span> <span class="p">=&gt;</span> <span class="p">{</span>
  <span class="k">try</span> <span class="p">{</span>
    <span class="kr">const</span> <span class="p">{</span> <span class="nx">code</span><span class="p">,</span> <span class="nx">data</span> <span class="p">}</span> <span class="o">=</span> <span class="kr">await</span> <span class="nx">somethingThatReturnsAPromise</span><span class="p">();</span>
  <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">err</span><span class="p">)</span> <span class="p">{</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="s1">&#39;request error&#39;</span><span class="p">,</span> <span class="nx">err</span><span class="p">);</span>
  <span class="p">}</span>
<span class="p">};</span>
</code></pre></td></tr></table>
</div>
</div><p>When the somethingThatReturnsAPromise() method throws a reject exception, it will be caught by catch.</p>
<p>Of course, async-await has another way of catching exceptions, by returning the correct data via await and writing <code>catch()</code> along with it, so that when the somethingThatReturnsAPromise() method throws an exception, it will automatically go to the catch() method.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span><span class="lnt">5
</span><span class="lnt">6
</span><span class="lnt">7
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-js" data-lang="js"><span class="kr">const</span> <span class="nx">request</span> <span class="o">=</span> <span class="kr">async</span> <span class="p">()</span> <span class="p">=&gt;</span> <span class="p">{</span>
  <span class="k">try</span> <span class="p">{</span>
    <span class="kr">const</span> <span class="p">{</span> <span class="nx">code</span><span class="p">,</span> <span class="nx">data</span> <span class="p">}</span> <span class="o">=</span> <span class="kr">await</span> <span class="nx">somethingThatReturnsAPromise</span><span class="p">().</span><span class="k">catch</span><span class="p">((</span><span class="nx">err</span><span class="p">)</span> <span class="p">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="s1">&#39;catch error&#39;</span><span class="p">,</span> <span class="nx">err</span><span class="p">));</span>
  <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">err</span><span class="p">)</span> <span class="p">{</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="s1">&#39;request error&#39;</span><span class="p">,</span> <span class="nx">err</span><span class="p">);</span>
  <span class="p">}</span>
<span class="p">};</span>
</code></pre></td></tr></table>
</div>
</div><p>However, after this catching of the exception, the catch() method of the outer layer does not catch the exception and does not continue to bubble up to the outer layer. The correct approach is that errors generated by the underlying module should be thrown directly to the business layer to let the business layer decide what to do with the error, rather than just swallowing it.</p>
<h3 id="14-multi-layer-try-catch">1.4 Multi-layer try-catch</h3>
<p>When multi-layer try-catch is used, it is caught by the innermost catch() method, and then it stops bubbling to the outer layer.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span><span class="lnt">5
</span><span class="lnt">6
</span><span class="lnt">7
</span><span class="lnt">8
</span><span class="lnt">9
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-js" data-lang="js"><span class="k">try</span> <span class="p">{</span>
  <span class="k">try</span> <span class="p">{</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="s1">&#39;error&#39;</span><span class="p">);</span>
  <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">err</span><span class="p">)</span> <span class="p">{</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="s1">&#39;内层的catch&#39;</span><span class="p">,</span> <span class="nx">err</span><span class="p">);</span> <span class="c1">// 内层的catch Error: error
</span><span class="c1"></span>  <span class="p">}</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">err</span><span class="p">)</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="s1">&#39;最外层的catch&#39;</span><span class="p">,</span> <span class="nx">error</span><span class="p">);</span>
<span class="p">}</span>
</code></pre></td></tr></table>
</div>
</div><p>Next, we understand the types of errors that occur in js.</p>
<h2 id="2-native-error-types">2. Native error types</h2>
<p>Before we get into using <code>try-catch</code>, let&rsquo;s understand what are the native error types in js.</p>
<p>There are six types of errors that can be generated by js code at runtime.</p>
<ul>
<li>SyntaxError.</li>
<li>TypeError.</li>
<li>rangeError.</li>
<li>evalError.</li>
<li>ReferenceError.</li>
<li>URI error.</li>
</ul>
<p>These error types all inherit from the <code>Error</code> class.</p>
<h3 id="21-syntaxerror">2.1 SyntaxError</h3>
<p>Syntax error, usually the developer in the development process, the code statement is written in a problem, the browser can not parse it.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-js" data-lang="js"><span class="kr">const</span> <span class="nx">a</span><span class="o">=</span><span class="p">;</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">a</span><span class="p">);</span> <span class="c1">// Uncaught SyntaxError: Unexpected token &#39;;&#39;
</span></code></pre></td></tr></table>
</div>
</div><h3 id="22-typeerror">2.2 TypeError</h3>
<p>Type errors usually occur in two cases.</p>
<ul>
<li>the operator is used on an improperly typed variable, such as a concat operation on a numeric type.</li>
<li>The operated variable encounters an unanticipated null or undefined value.</li>
</ul>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span><span class="lnt">5
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-js" data-lang="js"><span class="kr">const</span> <span class="nx">obj</span> <span class="o">=</span> <span class="p">{};</span>
<span class="nx">obj</span><span class="p">.</span><span class="nx">concat</span><span class="p">([</span><span class="mi">1</span><span class="p">]);</span> <span class="c1">// Uncaught TypeError: obj.concat is not a function
</span><span class="c1"></span>
<span class="kr">const</span> <span class="nx">a</span> <span class="o">=</span> <span class="kc">null</span><span class="p">;</span>
<span class="nx">a</span><span class="p">.</span><span class="nx">nickname</span><span class="p">;</span> <span class="c1">// Uncaught TypeError: Cannot read property &#39;nickname&#39; of null
</span></code></pre></td></tr></table>
</div>
</div><p>When writing methods to be called by other modules, a <code>TypeError</code> error can be thrown when checking for vacant parameters such as null or null.</p>
<h3 id="23-rangeerror">2.3 RangeError</h3>
<p>This error is usually caused by passing in parameters that are out of the specified range. For example, the <code>toFixed()</code> method can accept values in the range 0-100, and when this range is exceeded, the error is thrown.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-js" data-lang="js"><span class="nb">Math</span><span class="p">.</span><span class="nx">PI</span><span class="p">.</span><span class="nx">toFixed</span><span class="p">(</span><span class="mi">105</span><span class="p">);</span> <span class="c1">// Uncaught RangeError: toFixed() digits argument must be between 0 and 100
</span></code></pre></td></tr></table>
</div>
</div><h3 id="24-evalerror">2.4 evalError</h3>
<p>This type of error is generally rarely encountered, because other types of errors are thrown when using eval operations, even if they are not justified.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-js" data-lang="js"><span class="k">new</span> <span class="nb">eval</span><span class="p">();</span> <span class="c1">// Uncaught TypeError: eval is not a constructor
</span><span class="c1"></span><span class="nb">eval</span> <span class="o">=</span> <span class="mi">1234</span><span class="p">;</span> <span class="c1">// 正确执行
</span></code></pre></td></tr></table>
</div>
</div><h3 id="25-referenceerror">2.5 ReferenceError</h3>
<p>A reference error indicates that the master or apprentice is accessing an undeclared variable.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-js" data-lang="js"><span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">nick</span><span class="p">);</span> <span class="c1">// Uncaught ReferenceError: nick is not defined
</span></code></pre></td></tr></table>
</div>
</div><h3 id="26-uri-errors-urierror">2.6 URI errors (URIError)</h3>
<p>This error is usually thrown by some manipulation of uri functions, mainly: encodeURI(), decodeURI(), encodeURIComponent(), decodeURIComponent(), escape(), unescape().</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-js" data-lang="js"><span class="nb">decodeURIComponent</span><span class="p">(</span><span class="s1">&#39;%&#39;</span><span class="p">);</span> <span class="c1">// Uncaught URIError: URI malformed
</span><span class="c1"></span><span class="nb">decodeURIComponent</span><span class="p">(</span><span class="s1">&#39;%23&#39;</span><span class="p">);</span> <span class="c1">// # 正确执行
</span></code></pre></td></tr></table>
</div>
</div><h2 id="3-customizing-error-types">3. Customizing error types</h2>
<p>For slightly larger modules, we want to customize some error types by which we can tell that a module is throwing an error. How should we write this?</p>
<p>Our custom error types are also inherited from the <code>Error</code> class, which is very simple to implement.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt"> 1
</span><span class="lnt"> 2
</span><span class="lnt"> 3
</span><span class="lnt"> 4
</span><span class="lnt"> 5
</span><span class="lnt"> 6
</span><span class="lnt"> 7
</span><span class="lnt"> 8
</span><span class="lnt"> 9
</span><span class="lnt">10
</span><span class="lnt">11
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-js" data-lang="js"><span class="kr">class</span> <span class="nx">FingerError</span> <span class="kr">extends</span> <span class="nb">Error</span> <span class="p">{</span>
  <span class="nx">constructor</span><span class="p">(</span><span class="nx">message</span><span class="p">)</span> <span class="p">{</span>
    <span class="kr">super</span><span class="p">(</span><span class="nx">message</span><span class="p">);</span>
    <span class="k">this</span><span class="p">.</span><span class="nx">name</span> <span class="o">=</span> <span class="s1">&#39;FingerError&#39;</span><span class="p">;</span> <span class="c1">// 该错误的名称
</span><span class="c1"></span>    <span class="nb">Error</span><span class="p">.</span><span class="nx">captureStackTrace</span><span class="p">(</span><span class="k">this</span><span class="p">,</span> <span class="k">this</span><span class="p">.</span><span class="nx">constructor</span><span class="p">);</span> <span class="c1">// 获取错误堆栈的信息
</span><span class="c1"></span>  <span class="p">}</span>
<span class="p">}</span>

<span class="kr">const</span> <span class="nx">err</span> <span class="o">=</span> <span class="k">new</span> <span class="nx">FingerError</span><span class="p">(</span><span class="s1">&#39;get name error&#39;</span><span class="p">);</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">err</span><span class="p">);</span> <span class="c1">// FingerError: get name error
</span><span class="c1"></span><span class="nx">err</span> <span class="k">instanceof</span> <span class="nx">FingerError</span><span class="p">;</span> <span class="c1">// true
</span></code></pre></td></tr></table>
</div>
</div><h2 id="4-summary">4. Summary</h2>
<p>There are many ways to generate errors in the front end, and we should pay attention to avoid them. Next, we can also analyze how to monitor the errors and types of errors that occur in the page from the perspective of error monitoring.</p>

    </div>

    
<footer class="post-footer">
      <div class="post-tags">
          <a href="/tags/javascript/">javascript</a>
          </div>
      <nav class="post-nav">
        <a class="prev" href="/post/2022-02/js-eventloop/">
            <i class="iconfont icon-left"></i>
            <span class="prev-text nav-default">The EventLoop mechanism in Js</span>
            <span class="prev-text nav-mobile">Prev</span>
          </a>
        <a class="next" href="/post/2022-02/react-use-tips/">
            <span class="next-text nav-default">Some tips to help you in react development</span>
            <span class="next-text nav-mobile">Next</span>
            <i class="iconfont icon-right"></i>
          </a>
      </nav>
    </footer>
  </article>
        </div>
        

  

  

      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="social-links">
  <a href="https://www.sobyte.net/index.xml" type="application/rss+xml" class="iconfont icon-rss" title="rss"></a>
</div>

<div class="copyright">
  <span class="power-by">
    Powered by <a class="hexo-link" href="https://gohugo.io">Hugo</a>
  </span>
  <span class="division">|</span>
  <span class="theme-info">
    Theme - 
    <a class="theme-link" href="https://github.com/olOwOlo/hugo-theme-even">Even</a>
  </span>

  

  <span class="copyright-year">
    &copy; 
    2021 - 
    2022<span class="heart"><i class="iconfont icon-heart"></i></span><span></span>
  </span>
</div>

    </footer>

    <div class="back-to-top" id="back-to-top">
      <i class="iconfont icon-up"></i>
    </div>
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>



<script type="text/javascript" src="/js/main.min.c99b103c33d1539acf3025e1913697534542c4a5aa5af0ccc20475ed2863603b.js"></script>
  <script type="text/javascript">
    window.MathJax = {
      tex: {
        inlineMath: [['$','$'], ['\\(','\\)']],
        tags: 'ams',
        }
    };
  </script>
  <script async src="https://cdn.jsdelivr.net/npm/mathjax@3.0.5/es5/tex-mml-chtml.js" integrity="sha256-HGLuEfFcsUJGhvB8cQ8nr0gai9EucOOaIxFw7qxmd+w=" crossorigin="anonymous"></script>








</body>
</html>
